function onCreate()
--- SCORE:
	--- Shadows
	makeLuaText('scoretext3', 'score: ', 10, 0, 15)
	setTextBorder('scoretext3', 0, '000000')
    setTextSize('scoretext3', 50)
    setTextColor('scoretext3', '000000')
    setTextAlignment('scoretext3', 'left')
    setTextFont('scoretext3', 'sonic-genesis-hud-font.ttf')
    setProperty('scoretext3.visible', true)
	setProperty('scoretext3.antialiasing', false)
    addLuaText('scoretext3')
    setObjectCamera('scoretext3', 'other')

	makeLuaText('scoretext4', '             ', 0, 0, 15)
	setTextBorder('scoretext4', 0, '000000')
    setTextSize('scoretext4', 50)
    setTextColor('scoretext4', '000000')
    setTextAlignment('scoretext4', 'left')
    setTextFont('scoretext4', 'sonic-genesis-hud-font.ttf')
    setProperty('scoretext4.visible', true)
	setProperty('scoretext4.antialiasing', false)
    addLuaText('scoretext4')
    setObjectCamera('scoretext4', 'other')
	addLuaText('scoretext4')
	addLuaText('scoretext3')
	addLuaText('scoretext')
	addLuaText('scoretext2')

	--- Base
	makeLuaText('scoretext', 'score: ', 0, 0, 10)
    setTextSize('scoretext', 50)
    setTextColor('scoretext', 'ffd000')
    setTextAlignment('scoretext', 'left')
    setTextFont('scoretext', 'sonic-genesis-hud-font.ttf')
    setProperty('scoretext.visible', true)
	setProperty('scoretext.antialiasing', false)
    addLuaText('scoretext')
    setObjectCamera('scoretext', 'other')
	setTextItalic('scoretext', true)

	makeLuaText('scoretext2', '             ', 0, 5, 10)
    setTextSize('scoretext2', 50)
    setTextColor('scoretext2', 'ffffff')
    setTextAlignment('scoretext2', 'left')
    setTextFont('scoretext2', 'sonic-genesis-hud-font.ttf')
    setProperty('scoretext2.visible', true)
	setProperty('scoretext2.antialiasing', false)
    addLuaText('scoretext2')
    setObjectCamera('scoretext2', 'other')
	
--- MISSES:
	--- Shadows
	makeLuaText('missestext3', 'misses: ', 0, 0, 65)
	setTextBorder('missestext3', 0, '000000')
    setTextSize('missestext3', 50)
    setTextColor('missestext3', '000000')
    setTextAlignment('missestext3', 'left')
    setTextFont('missestext3', 'sonic-genesis-hud-font.ttf')
    setProperty('missestext3.visible', true)
	setProperty('missestext3.antialiasing', false)
    addLuaText('missestext3')
    setObjectCamera('missestext3', 'other')

	makeLuaText('missestext4', '             ', 0, 0, 65)
	setTextBorder('missestext4', 0, '000000')
    setTextSize('missestext4', 50)
    setTextColor('missestext4', '000000')
    setTextAlignment('missestext4', 'left')
    setTextFont('missestext4', 'sonic-genesis-hud-font.ttf')
    setProperty('missestext4.visible', true)
	setProperty('missestext4.antialiasing', false)
    addLuaText('missestext4')
    setObjectCamera('missestext4', 'other')
	addLuaText('missestext4')
	addLuaText('missestext3')
	addLuaText('missestext')
	addLuaText('missestext2')

	--- Base
	makeLuaText('missestext', 'misses: ', 0, 0, 60)
    setTextSize('missestext', 50)
    setTextColor('missestext', 'ffd000')
    setTextAlignment('missestext', 'left')
    setTextFont('missestext', 'sonic-genesis-hud-font.ttf')
    setProperty('missestext.visible', true)
	setProperty('missestext.antialiasing', false)
    addLuaText('missestext')
    setObjectCamera('missestext', 'other')

	makeLuaText('missestext2', '             ', 0, 4, 60)
    setTextSize('missestext2', 50)
    setTextColor('missestext2', 'ffffff')
    setTextAlignment('missestext2', 'left')
    setTextFont('missestext2', 'sonic-genesis-hud-font.ttf')
    setProperty('missestext2.visible', true)
	setProperty('missestext2.antialiasing', false)
    addLuaText('missestext2')
    setObjectCamera('missestext2', 'other')
	
--- RATING:
	--- Shadows
	makeLuaText('ratingtext3', 'rating: ', 0, 0, 115)
	setTextBorder('ratingtext3', 0, '000000')
    setTextSize('ratingtext3', 50)
    setTextColor('ratingtext3', '000000')
    setTextAlignment('ratingtext3', 'left')
    setTextFont('ratingtext3', 'sonic-genesis-hud-font.ttf')
    setProperty('ratingtext3.visible', true)
	setProperty('ratingtext3.antialiasing', false)
    addLuaText('ratingtext3')
    setObjectCamera('ratingtext3', 'other')

	makeLuaText('ratingtext4', '             ', 0, 0, 115)
	setTextBorder('ratingtext4', 0, '000000')
    setTextSize('ratingtext4', 50)
    setTextColor('ratingtext4', '000000')
    setTextAlignment('ratingtext4', 'left')
    setTextFont('ratingtext4', 'sonic-genesis-hud-font.ttf')
    setProperty('ratingtext4.visible', true)
	setProperty('ratingtext4.antialiasing', false)
    addLuaText('ratingtext4')
    setObjectCamera('ratingtext4', 'other')
	addLuaText('ratingtext4')
	addLuaText('ratingtext3')
	addLuaText('ratingtext')
	addLuaText('ratingtext2')

	--- Base
	makeLuaText('ratingtext', 'rating: ', 0, 0, 110)
    setTextSize('ratingtext', 50)
    setTextColor('ratingtext', 'ffd000')
    setTextAlignment('ratingtext', 'left')
    setTextFont('ratingtext', 'sonic-genesis-hud-font.ttf')
    setProperty('ratingtext.visible', true)
	setProperty('ratingtext.antialiasing', false)
    addLuaText('ratingtext')
    setObjectCamera('ratingtext', 'other')

	makeLuaText('ratingtext2', '             ', 0, 5, 110)
    setTextSize('ratingtext2', 50)
    setTextColor('ratingtext2', 'ffffff')
    setTextAlignment('ratingtext2', 'left')
    setTextFont('ratingtext2', 'sonic-genesis-hud-font.ttf')
    setProperty('ratingtext2.visible', true)
	setProperty('ratingtext2.antialiasing', false)
    addLuaText('ratingtext2')
    setObjectCamera('ratingtext2', 'other')
end

function onUpdate(elapsed)
	setTextString('scoretext2', '                '..getProperty('songScore'))
	setTextString('scoretext4', '                '..getProperty('songScore'))
	setTextString('missestext2', '                   '..getProperty('songMisses'))
	setTextString('missestext4', '                   '..getProperty('songMisses'))
	setTextString('ratingtext2', '                  '..getProperty('ratingName'))
	setTextString('ratingtext4', '                  '..getProperty('ratingName'))
end